### ISSUE TITLE
Ajouter des options dans le script check.py afin de pouvoir sélectionner les checker qui seront utilisés

### ISSUE THREAD

**Issue by Amiralgaby** [mothsART/wiki-corrector#17]
Explication sur ce que je souhaite faire : ça serait plusieurs options qui permet de sélectionner quels "checker" seront utilisés lors de l'exécution du script.

Par exemple
./check -u # pour le checker Url
./check -d # Dokuwiki
./check -g # grammar
./check -s # shell
./check -p # apturl
./check -n # notallowed

Bien sûr, j'espère pour réussir à faire combiner le tout avec "-a" ou "--all-checker"

./check -a

J'espère pour réussir facilement cela.

**Comment by mothsART** [comment]
Oui, bonne initiative. C'est vrai que tant que j'étais tout seul, je m'en sortais en commentant/décommentant du code mais ça serait plus pérenne

**Comment by mothsART** [comment]
tu peux sans doute utiliser une lib tel que https://click.palletsprojects.com/en/8.1.x/  et la rajouter dans https://github.com/mothsART/wiki-corrector/blob/main/requirements.txt
Ca devrait te simplifier la vie
