### ISSUE TITLE
question rapide by the way

### ISSUE THREAD

**Issue by Amiralgaby** [mothsART/wiki-corrector#2]
N'existe t-il pas des regex pour l'extraction des URL, plutôt que d'extraire en supposant que toutes les URL sont bonnes tant que la syntaxe dokuwiki n'apparaît pas ?

oui je me prends trop la tête. 🤣 

Ce site donne un regex pour les URL
https://www.urlregex.com/

**Comment by mothsART** [comment]
Tu veux déterminer que l'url est "valide" pour éviter une requète j'imagine.
C'est pas con comme idée mais est-ce que ça va vraiment avoir une plus-value... pas certain.

**Comment by Amiralgaby** [comment]
Oui c'est ça. La plus value serait d'éviter d'avoir des URL invalides. ça évite de se baser sur la syntaxe dokuwiki.

Moi non plus je suis pas certain qu'il y est meilleur après avoir mis toutes les syntaxes possible par dokuwiki

**Comment by mothsART** [comment]
Mais si l'URL est invalide, aiohttp va de toute façon remonter une erreur...
Du coup, je vois plus vraiment d'intérêt.
