### ISSUE TITLE
Demande Exclusion Article

### ISSUE THREAD

**Issue by dexter74** [mothsART/wiki-corrector#9]
Bonjour,

Je souhaiterai que la page "dexter74.dokuwiki" soit exclus svp. (privée)

Merci d'avance.

L'auteur de la page .

**Comment by mothsART** [comment]
J'ai fait ici : https://github.com/mothsART/wiki-corrector/commit/cd12bfc6068fa75fe798cba36fe4096c1ebd125d
E revanche, j'ai du mal à comprendre le besoin vu que la page est publique.
